### ISSUE TITLE
null pointer exceptio

### ISSUE THREAD

**Issue by xflowx** [Minecraft-Technik-Wiki/BlockMap#12]
Hi,

Great software, i tried it today for the first time: it renders only some chunks, rest stays "blue". I have attached the output from the commandline.

Ubuntu 18.04
OpenJDK-8

regards,
flo
[log.txt](https://github.com/Minecraft-Technik-Wiki/BlockMap/files/2626639/log.txt)

**Comment by piegamesde** [comment]
Can you please mail me or upload the world for debugging? (Only the file `./region/r.-1.-2.mca` should be fine)

**Comment by xflowx** [comment]
Here you are, thanks for looking into it!
[r.-1.-2.zip](https://github.com/Minecraft-Technik-Wiki/BlockMap/files/2645865/r.-1.-2.zip)

**Comment by piegamesde** [comment]
I can indeed reproduce the issue. I loaded one of the crashing chunks into NBTExplorer and it looks pretty broken:
![image](https://user-images.githubusercontent.com/14054505/49515949-972fa680-f898-11e8-96c2-c1e5cef43bc5.png)
If you compare it to the specification (https://minecraft.gamepedia.com/Chunk_format), you'll see that `Y: -1` is not a valid value and that each section in the chunk must have a `Palette` entry.

I then copied the region file into a test world, and indeed Minecraft threw errors and didn't load the broken chunks. It even froze my computer on saving.

So your world seems to be corrupt. I'll add some better logging and error handling rather than a generic exception.

**Comment by xflowx** [comment]
That is really strange, because i can play this map without any problems.
But indeed its strange, because there are several region files in the folder, which i never visited, and thus are completely empty... so definitely i can not find any corrupted chunks in the world.

**Comment by piegamesde** [comment]
Can you reproduce this issue with other maps or world data?

**Comment by xflowx** [comment]
Today i created a world in the current snapshot, 18w49a, and tried to map it.
i got no error message, but also no results(only light blue tiles)
also here i can see the entries with Y: -1
[region.zip](https://github.com/Minecraft-Technik-Wiki/BlockMap/files/2664714/region.zip)

also, i created many new chunks in the other map, same there: in every new chunk there is an entry Y:-1
Unfortunately, i can also find no reference about this value..

**Comment by piegamesde** [comment]
It seems we might have a major issue here. Can you please help me to create worlds that reproduce the issue? For this, I'd need:

- The Minecraft version (including mods, if present)
- The seed and world generation settings to use
- Your operating system
- The coordinates of chunks that don't render
- Any error logs

Please use the newly released version 1.2, since I've improved the error messages with corrupt worlds.
