### ISSUE TITLE
1.16 Support?

### ISSUE THREAD

**Issue by unsupervisednn** [Minecraft-Technik-Wiki/BlockMap#43]
1.16 was released today, block map is unable to render any of the chunks for it.

```
Failed to render chunk (5, 5) section 3. This is very likely because your chunk is corrupt. If possible, please verify it manually before sending a bug report.
```

**Comment by piegamesde** [comment]
I originally planned to update it last weekend, but I'm pretty busy right now and that sadly didn't happen. While initial 1.16 support (e.g. not crashing on newer chunks) should be quite easy to implement, all of the new features will take some time.

I'd appreciate some contributions regarding this and I'm willing to help anyone who wants to tackle the issue. There is some high-level documentation about this [in the Readme](https://github.com/Minecraft-Technik-Wiki/BlockMap#update-to-newer-minecraft-version). (Otherwise, I'll have a look into it my self probably at the end of the week).

**Comment by piegamesde** [comment]
Initial 1.16 support can now be found on the master branch. Sadly, most chunks don't render at all because of changes in the save format. The changelog says:

> Block storage format in chunks slightly changed to speed up various tasks (rendering, pathfinding, world generation, etc).

Sadly, they do not say *what* changed, so someone will have to dig the source code and reverse-engineer it. (Alternatively, we'll have to wait until someone from the Minecraft Wiki does it).

----

The other thing to do is to add in all the new blocks, points of interest etc. I've created [a project](https://github.com/Minecraft-Technik-Wiki/BlockMap/projects/5) to track things that are left to do. Again, contributions welcome!

**Comment by piegamesde** [comment]
https://github.com/Minecraft-Technik-Wiki/BlockMap/releases/tag/2.1.0
